Add next and previous buttons for about pages
LBHackney-IT/developers-hub-frontend pull request #41
Opened 2022-01-31 14:49 UTC by elena-evans

- added buttons
- styled buttons
- ensured mobile responsiveness

2022-01-31 17:14 UTC, notatiyyah commented on src/pages/home/home.style.scss
> +.buttonStyling {
I'd recommend improving this class name (e.g. `home-page-nav-button`) and removing the `!important`s.

Here's a stack overflow answer that explains why it's better not to use `!important`: https://stackoverflow.com/questions/3706819/what-are-the-implications-of-using-important-in-css

2022-02-01 10:29 UTC, elena-evans commented on src/pages/home/home.style.scss
> +.buttonStyling {
Thanks! I've just pushed these changes

2022-02-01 14:02 UTC, notatiyyah approved these changes

2022-02-01 16:30 UTC, humulla requested changes
The first page shouldn't have a previous button and the last page shouldn't have a next button . Would it be possible for you to add functionality for that with TDD? Thank you

2022-02-02 10:54 UTC, humulla approved these changes

2022-02-02 11:02 UTC, merged